/**
 * Generates `src/db/schema.mirror.ts` from `src/mirror/endpoints.ts`.
 *
 *   deno task db:gen-mirror
 *
 * The canonical tables have ~130 columns between them, all mechanically derived
 * from IGDB's dump schema, so they are generated rather than hand-typed. The
 * output IS committed — drizzle-kit reads it to produce migrations, and the
 * derive layer imports it like any other schema file. Re-run this after editing
 * the column lists in `endpoints.ts`, then `deno task db:generate`.
 */

import {
	columnsOf,
	type DumpType,
	ENDPOINT_NAMES,
	type Endpoint,
	EXTRA_COLUMNS,
	tableName,
} from '../mirror/endpoints.js'

const OUT = new URL('../db/schema.mirror.ts', import.meta.url)

/** Drizzle column builder for each dump type. `%s` is the SQL column name. */
const BUILDER: Record<DumpType, (name: string) => string> = {
	LONG: (n) => `bigint('${n}', { mode: 'number' })`,
	INTEGER: (n) => `integer('${n}')`,
	DOUBLE: (n) => `doublePrecision('${n}')`,
	STRING: (n) => `text('${n}')`,
	TIMESTAMP: (n) => `timestamp('${n}', { withTimezone: true })`,
	UUID: (n) => `uuid('${n}')`,
	BOOLEAN: (n) => `boolean('${n}')`,
	'LONG[]': (n) => `bigint('${n}', { mode: 'number' }).array()`,
	'INTEGER[]': (n) => `integer('${n}').array()`,
}

/** snake_case -> camelCase, for the TS-side property name. */
function camel(s: string): string {
	return s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())
}

/** `games` -> `igdbGames`. */
function exportName(endpoint: Endpoint): string {
	return `igdb${camel(endpoint).replace(/^./, (c) => c.toUpperCase())}`
}

/**
 * Which columns get an index, beyond the `id` primary key.
 *
 * Every child table is looked up by `game` during derive, and `games` is walked
 * by slug (routes), by parent (root resolution), and by relation arrays (the
 * fold subtree walk — those need GIN, added in `extraSql` below).
 */
const INDEXED: Partial<Record<Endpoint, string[]>> = {
	games: ['slug', 'parent_game', 'version_parent', 'game_type', 'updated_at'],
	covers: ['game'],
	involved_companies: ['game', 'company'],
	release_dates: ['game'],
	websites: ['game'],
	external_games: ['game', 'uid'],
	alternative_names: ['game'],
}

function renderTable(endpoint: Endpoint): string {
	const table = tableName(endpoint)
	const lines: string[] = []

	for (const [name, type] of columnsOf(endpoint)) {
		let expr = BUILDER[type](name)
		if (name === 'id') expr += '.primaryKey()'
		lines.push(`\t${camel(name)}: ${expr},`)
	}

	for (const [name, sql] of Object.entries(EXTRA_COLUMNS[endpoint] ?? {})) {
		// Only bigint extras exist today; widen this if that changes.
		if (sql !== 'bigint') throw new Error(`Unhandled extra column type: ${sql}`)
		lines.push(`\t${camel(name)}: bigint('${name}', { mode: 'number' }),`)
	}

	lines.push(
		`\tmirrorUpdatedAt: timestamp('mirror_updated_at', { withTimezone: true }).notNull().defaultNow(),`,
	)
	lines.push(`\tdeletedAt: timestamp('deleted_at', { withTimezone: true }),`)

	const idx = (INDEXED[endpoint] ?? [])
		.map((c) => `\t\tindex('${table}_${c}_idx').on(t.${camel(c)}),`)
		.join('\n')

	const indexBlock = idx ? `, (t) => [\n${idx}\n\t]` : ''

	return `export const ${exportName(endpoint)} = pgTable('${table}', {\n${lines.join(
		'\n',
	)}\n}${indexBlock})\n`
}

const body = ENDPOINT_NAMES.map(renderTable).join('\n')

const source = `// Code generated by \`deno task db:gen-mirror\`. DO NOT EDIT.
//
// Source of truth: src/mirror/endpoints.ts. Layer 1 (canonical) of
// docs/PLAN-igdb-mirror.md — a 1:1 mirror of IGDB's data dumps that is never
// hand-edited. Every augmentation lives downstream in the derived layer.

import {
\tbigint,
\tboolean,
\tdoublePrecision,
\tindex,
\tinteger,
\tpgTable,
\ttext,
\ttimestamp,
\tuuid,
} from 'drizzle-orm/pg-core'

${body}`

await Deno.writeTextFile(OUT, source)
console.log(`Wrote ${OUT.pathname} (${ENDPOINT_NAMES.length} tables)`)
